/**
 * Detect auto-generated messages the application must not auto-respond to.
 *
 * Without this check, an auto-reply to an auto-reply creates an infinite mail
 * loop. RFC 3834 (Auto-Submitted) and common practice (Precedence,
 * X-Auto-Response-Suppress) are the universally-honored signals.
 */
export function isAutoGeneratedMessage(headers: Record<string, string>): boolean {
  const autoSubmitted = headers['auto-submitted']?.toLowerCase().trim()
  if (autoSubmitted && autoSubmitted !== 'no') return true

  const precedence = headers['precedence']?.toLowerCase().trim()
  if (precedence === 'bulk' || precedence === 'junk' || precedence === 'list') return true

  if (headers['x-auto-response-suppress']) return true

  return false
}
