import { MailInboundError } from '../inbound_error.ts'
import { isAutoGeneratedMessage } from './loop_guard.ts'
import type {
  InboundWebhookInput,
  InboundWebhookParser,
  ParsedInboundAddress,
  ParsedInboundAttachment,
  ParsedInboundMail,
} from './types.ts'

/**
 * Parse a Postmark Inbound webhook payload into `ParsedInboundMail`.
 *
 * Postmark does NOT sign inbound webhooks with HMAC. Authenticate the request
 * at the HTTP layer — Basic Auth on the webhook URL and/or IP allow-listing —
 * before handing the body to this parser.
 *
 * @see https://postmarkapp.com/developer/user-guide/inbound/parse-an-email
 */
export class PostmarkInboundParser implements InboundWebhookParser {
  async parse(input: InboundWebhookInput): Promise<ParsedInboundMail> {
    const payload = this.decode(input.body)
    const headers = this.extractHeaders(payload.Headers ?? [])

    const from = this.mapAddress(payload.FromFull) ?? {
      address: payload.From ?? '',
      ...(payload.FromName ? { name: payload.FromName } : {}),
    }

    const to = mapList(payload.ToFull, (a) => this.mapAddress(a))
    const cc = mapList(payload.CcFull, (a) => this.mapAddress(a))
    const bcc = mapList(payload.BccFull, (a) => this.mapAddress(a))
    const replyTo = payload.ReplyTo ? { address: payload.ReplyTo } : undefined

    return {
      from,
      to,
      cc,
      bcc,
      replyTo,
      subject: payload.Subject ?? '',
      text: payload.TextBody || undefined,
      html: payload.HtmlBody || undefined,
      date: payload.Date ? new Date(payload.Date) : undefined,
      headers,
      attachments: this.mapAttachments(payload.Attachments ?? []),
      messageId: stripAngles(headers['message-id']),
      inReplyTo: stripAngles(headers['in-reply-to']),
      references: parseReferences(headers['references']),
      isAutoGenerated: isAutoGeneratedMessage(headers),
      providerMessageId: payload.MessageID,
    }
  }

  private decode(body: string | Buffer): PostmarkInboundPayload {
    try {
      const text = typeof body === 'string' ? body : body.toString('utf-8')
      return JSON.parse(text) as PostmarkInboundPayload
    } catch (err) {
      throw new MailInboundError(
        `Postmark inbound webhook: invalid JSON payload — ${(err as Error).message}`,
        { context: { provider: 'postmark' }, cause: err },
      )
    }
  }

  private mapAddress(addr?: PostmarkAddress): ParsedInboundAddress | undefined {
    if (!addr?.Email) return undefined
    return addr.Name ? { address: addr.Email, name: addr.Name } : { address: addr.Email }
  }

  private extractHeaders(headers: PostmarkHeader[]): Record<string, string> {
    const result: Record<string, string> = {}
    for (const h of headers) {
      if (h.Name) result[h.Name.toLowerCase()] = h.Value
    }
    return result
  }

  private mapAttachments(atts: PostmarkAttachment[]): ParsedInboundAttachment[] {
    return atts.map((a) => {
      const cid = a.ContentID ? stripAngles(a.ContentID) : undefined
      return {
        filename: a.Name,
        contentType: a.ContentType,
        content: Buffer.from(a.Content, 'base64'),
        size: a.ContentLength,
        ...(cid ? { cid } : {}),
      }
    })
  }
}

interface PostmarkAddress {
  Email: string
  Name?: string
  MailboxHash?: string
}

interface PostmarkHeader {
  Name: string
  Value: string
}

interface PostmarkAttachment {
  Name: string
  ContentType: string
  Content: string
  ContentLength: number
  ContentID?: string | null
}

interface PostmarkInboundPayload {
  From?: string
  FromName?: string
  FromFull?: PostmarkAddress
  To?: string
  ToFull?: PostmarkAddress[]
  Cc?: string
  CcFull?: PostmarkAddress[]
  Bcc?: string
  BccFull?: PostmarkAddress[]
  ReplyTo?: string
  Subject?: string
  MessageID?: string
  Date?: string
  TextBody?: string
  HtmlBody?: string
  Headers?: PostmarkHeader[]
  Attachments?: PostmarkAttachment[]
}

function mapList<T, R>(list: T[] | undefined, fn: (item: T) => R | undefined): NonNullable<R>[] {
  if (!list) return []
  const out: NonNullable<R>[] = []
  for (const item of list) {
    const mapped = fn(item)
    if (mapped !== undefined && mapped !== null) out.push(mapped as NonNullable<R>)
  }
  return out
}

function stripAngles(value: string | undefined): string | undefined {
  if (!value) return undefined
  const trimmed = value.trim()
  if (trimmed.startsWith('<') && trimmed.endsWith('>')) {
    const inner = trimmed.slice(1, -1).trim()
    return inner || undefined
  }
  return trimmed || undefined
}

function parseReferences(value: string | undefined): string[] {
  if (!value) return []
  return value
    .split(/\s+/)
    .map((ref) => stripAngles(ref))
    .filter((v): v is string => Boolean(v))
}
