/**
 * Inbound mail types.
 *
 * Provider webhooks (Postmark / Mailgun) — and any future driver — all
 * normalize to `ParsedInboundMail` so application code can consume inbound
 * mail from any source uniformly.
 */

export interface ParsedInboundAddress {
  address: string
  name?: string
}

export interface ParsedInboundAttachment {
  filename: string
  contentType: string
  content: Buffer
  size: number
  /** Content-ID for inline images, angle brackets stripped. */
  cid?: string
}

export interface ParsedInboundMail {
  from: ParsedInboundAddress
  to: ParsedInboundAddress[]
  cc: ParsedInboundAddress[]
  bcc: ParsedInboundAddress[]
  replyTo?: ParsedInboundAddress
  subject: string
  text?: string
  html?: string
  date?: Date
  /**
   * Lowercased header name → value. Duplicate headers keep the last value;
   * widen to `string | string[]` if a future driver needs to preserve duplicates.
   */
  headers: Record<string, string>
  attachments: ParsedInboundAttachment[]
  /** RFC 5322 Message-ID of the inbound message, angle brackets stripped. */
  messageId?: string
  /** In-Reply-To header value, angle brackets stripped. */
  inReplyTo?: string
  /** References header parsed into a list, angle brackets stripped. */
  references: string[]
  /**
   * True if the message looks auto-generated (auto-reply, vacation, bulk, list).
   * Applications must not auto-respond when this is true — skipping this check
   * causes mail loops.
   */
  isAutoGenerated: boolean
  /** Provider's own message identifier (e.g. Postmark MessageID), if any. */
  providerMessageId?: string
}

export interface InboundWebhookInput {
  /**
   * Raw request body. `Buffer` preferred so signature checks see the exact
   * bytes the provider signed.
   */
  body: string | Buffer
  /** Request headers. Keys must be lowercased by the caller. */
  headers: Record<string, string | undefined>
}

export interface InboundWebhookParser {
  parse(input: InboundWebhookInput): Promise<ParsedInboundMail>
}

// -- Mailgun Routes webhook ---------------------------------------------------

export interface MailgunInboundConfig {
  /**
   * Mailgun "HTTP webhook signing key" from the dashboard — distinct from the
   * sending API key. Rotating it in the dashboard requires rotating here too.
   */
  webhookSigningKey: string
  /**
   * Reject signatures whose timestamp is older than N seconds. Default 300
   * (5 minutes). Tightens replay protection; widen only if clock skew is an issue.
   */
  maxAgeSeconds?: number
}
