// Public API of @strav/mail — mail layer.
//
// Shipping:
//   - The `Message` shape + `MailRecipient` / `MailAddress` /
//     `MessageAttachment`.
//   - The `Transport` driver contract.
//   - Two transports: `ArrayTransport` (in-memory recorder for tests)
//     + `LogTransport` (writes to a `Logger` channel — local-dev).
//   - `MailManager` — multi-transport orchestration with `via(name?)`,
//     default-`from` substitution, lazy/cached transport construction,
//     and a Mailable-aware `send(MailableClass, payload)` overload.
//   - `MailProvider` — wires `MailManager` into the container from
//     `config('mail')`.
//   - `Mailable<TPayload>` — typed `Job` subclass; `build(payload)` is
//     the override point, `handle()` is auto-implemented to send via
//     the default transport. Dispatch via `queue.dispatch(MailableClass,
//     payload)` like any other Job.
//
// Inbound webhooks:
//   - `PostmarkInboundParser` + `MailgunInboundParser` normalize provider
//     webhooks to `ParsedInboundMail`. Mailgun verifies HMAC-SHA256;
//     Postmark relies on HTTP-level auth (Basic/IP allow-list).
//   - `isAutoGeneratedMessage` — mail-loop guard for application code.
//
// Notifications, broadcast, and SSE live in `@strav/notification`.

export { isAutoGeneratedMessage } from './inbound/loop_guard.ts'
export { MailgunInboundParser } from './inbound/mailgun_parser.ts'
export { PostmarkInboundParser } from './inbound/postmark_parser.ts'
export type {
  InboundWebhookInput,
  InboundWebhookParser,
  MailgunInboundConfig,
  ParsedInboundAddress,
  ParsedInboundAttachment,
  ParsedInboundMail,
} from './inbound/types.ts'
export { MailInboundError } from './inbound_error.ts'
export { type MailConfig, MailManager, type MailTransportConfig } from './mail_manager.ts'
export { MailProvider } from './mail_provider.ts'
export { Mailable, type MailableClass, type MailablePayloadOf } from './mailable.ts'
export type { MailAddress, MailRecipient, Message, MessageAttachment } from './message.ts'
export type { Transport } from './transport.ts'
export { MailTransportError } from './transport_error.ts'
export {
  AlibabaDmTransport,
  type AlibabaDmTransportOptions,
} from './transports/alibaba_transport.ts'
export { ArrayTransport } from './transports/array_transport.ts'
export { LogTransport, type LogTransportOptions } from './transports/log_transport.ts'
export { MailgunTransport, type MailgunTransportOptions } from './transports/mailgun_transport.ts'
export { ResendTransport, type ResendTransportOptions } from './transports/resend_transport.ts'
export {
  SendGridTransport,
  type SendGridTransportOptions,
} from './transports/sendgrid_transport.ts'
