import { describe, expect, test } from 'bun:test'
import { createHmac } from 'node:crypto'
import { AuthError, ConfigError } from '@strav/kernel'
import { MailgunInboundParser } from '../src/inbound/mailgun_parser.ts'
import type { InboundWebhookInput } from '../src/inbound/types.ts'
import { MailInboundError } from '../src/inbound_error.ts'

const SIGNING_KEY = 'test-signing-key'

function signMailgun(timestamp: string, token: string, key = SIGNING_KEY): string {
  return createHmac('sha256', key)
    .update(timestamp + token)
    .digest('hex')
}

function currentTimestamp(offsetSec = 0): string {
  return String(Math.floor(Date.now() / 1000) + offsetSec)
}

async function buildMailgunRequest(
  fields: Record<string, string>,
  attachments: { name: string; contentType: string; content: string }[] = [],
): Promise<InboundWebhookInput> {
  const form = new FormData()
  for (const [name, value] of Object.entries(fields)) {
    form.set(name, value)
  }
  for (let i = 0; i < attachments.length; i++) {
    const a = attachments[i]!
    form.set(`attachment-${i + 1}`, new File([a.content], a.name, { type: a.contentType }))
  }
  if (attachments.length > 0) {
    form.set('attachment-count', String(attachments.length))
  }

  const response = new Response(form)
  const contentType = response.headers.get('content-type') ?? 'multipart/form-data'
  const body = Buffer.from(await response.arrayBuffer())

  return { body, headers: { 'content-type': contentType } }
}

function signedFields(overrides: Record<string, string> = {}): Record<string, string> {
  const timestamp = overrides['timestamp'] ?? currentTimestamp()
  const token = overrides['token'] ?? 'a'.repeat(50)
  const signature = overrides['signature'] ?? signMailgun(timestamp, token)
  return {
    timestamp,
    token,
    signature,
    sender: 'sender@example.com',
    from: '"Sender" <sender@example.com>',
    recipient: 'support@example.com',
    subject: 'Hello',
    'body-plain': 'Plain body',
    'body-html': '<p>HTML body</p>',
    'message-headers': JSON.stringify([
      ['Message-Id', '<abc@example.com>'],
      ['From', '"Sender" <sender@example.com>'],
      ['To', 'support@example.com'],
      ['Subject', 'Hello'],
    ]),
    ...overrides,
  }
}

describe('MailgunInboundParser', () => {
  test('parses a valid signed payload', async () => {
    const parser = new MailgunInboundParser({ webhookSigningKey: SIGNING_KEY })
    const input = await buildMailgunRequest(signedFields())
    const result = await parser.parse(input)

    expect(result.from).toEqual({ address: 'sender@example.com', name: 'Sender' })
    expect(result.to).toEqual([{ address: 'support@example.com' }])
    expect(result.subject).toBe('Hello')
    expect(result.text).toBe('Plain body')
    expect(result.html).toBe('<p>HTML body</p>')
    expect(result.messageId).toBe('abc@example.com')
    expect(result.isAutoGenerated).toBe(false)
  })

  test('rejects payload with tampered signature', async () => {
    const parser = new MailgunInboundParser({ webhookSigningKey: SIGNING_KEY })
    const input = await buildMailgunRequest(signedFields({ signature: 'a'.repeat(64) }))

    await expect(parser.parse(input)).rejects.toBeInstanceOf(AuthError)
  })

  test('rejects payload signed with the wrong key', async () => {
    const parser = new MailgunInboundParser({ webhookSigningKey: SIGNING_KEY })
    const timestamp = currentTimestamp()
    const token = 'b'.repeat(50)
    const wrongSig = signMailgun(timestamp, token, 'different-key')
    const input = await buildMailgunRequest(signedFields({ timestamp, token, signature: wrongSig }))

    await expect(parser.parse(input)).rejects.toBeInstanceOf(AuthError)
  })

  test('rejects stale timestamps (replay protection)', async () => {
    const parser = new MailgunInboundParser({ webhookSigningKey: SIGNING_KEY })
    const oldTs = currentTimestamp(-3600)
    const token = 'c'.repeat(50)
    const sig = signMailgun(oldTs, token)
    const input = await buildMailgunRequest(
      signedFields({ timestamp: oldTs, token, signature: sig }),
    )

    await expect(parser.parse(input)).rejects.toBeInstanceOf(AuthError)
  })

  test('rejects missing signature fields', async () => {
    const parser = new MailgunInboundParser({ webhookSigningKey: SIGNING_KEY })
    const fields = signedFields()
    delete fields['signature']
    const input = await buildMailgunRequest(fields)

    await expect(parser.parse(input)).rejects.toBeInstanceOf(AuthError)
  })

  test('rejects non-multipart content-types', async () => {
    const parser = new MailgunInboundParser({ webhookSigningKey: SIGNING_KEY })
    const input: InboundWebhookInput = {
      body: JSON.stringify(signedFields()),
      headers: { 'content-type': 'application/json' },
    }

    await expect(parser.parse(input)).rejects.toBeInstanceOf(MailInboundError)
  })

  test('throws ConfigError when webhookSigningKey is missing', () => {
    expect(() => new MailgunInboundParser({ webhookSigningKey: '' })).toThrow(ConfigError)
  })

  test('extracts threading headers from message-headers JSON', async () => {
    const parser = new MailgunInboundParser({ webhookSigningKey: SIGNING_KEY })
    const input = await buildMailgunRequest(
      signedFields({
        'message-headers': JSON.stringify([
          ['Message-Id', '<reply@example.com>'],
          ['In-Reply-To', '<parent@example.com>'],
          ['References', '<root@example.com> <parent@example.com>'],
        ]),
      }),
    )

    const result = await parser.parse(input)

    expect(result.messageId).toBe('reply@example.com')
    expect(result.inReplyTo).toBe('parent@example.com')
    expect(result.references).toEqual(['root@example.com', 'parent@example.com'])
  })

  test('flags auto-generated via Auto-Submitted in message-headers', async () => {
    const parser = new MailgunInboundParser({ webhookSigningKey: SIGNING_KEY })
    const input = await buildMailgunRequest(
      signedFields({
        'message-headers': JSON.stringify([['Auto-Submitted', 'auto-replied']]),
      }),
    )

    const result = await parser.parse(input)
    expect(result.isAutoGenerated).toBe(true)
  })

  test('decodes attachments from attachment-N fields', async () => {
    const parser = new MailgunInboundParser({ webhookSigningKey: SIGNING_KEY })
    const input = await buildMailgunRequest(signedFields(), [
      { name: 'note.txt', contentType: 'text/plain', content: 'hello' },
      { name: 'data.bin', contentType: 'application/octet-stream', content: 'xyz' },
    ])

    const result = await parser.parse(input)

    expect(result.attachments).toHaveLength(2)
    expect(result.attachments[0]!.filename).toBe('note.txt')
    expect(result.attachments[0]!.content.toString('utf-8')).toBe('hello')
    expect(result.attachments[1]!.filename).toBe('data.bin')
  })

  test('parses multi-recipient To field', async () => {
    const parser = new MailgunInboundParser({ webhookSigningKey: SIGNING_KEY })
    const input = await buildMailgunRequest(
      signedFields({ recipient: 'alice@example.com, bob@example.com' }),
    )

    const result = await parser.parse(input)
    expect(result.to.map((t) => t.address)).toEqual(['alice@example.com', 'bob@example.com'])
  })

  test('signature verification is constant-time (different-length signatures rejected)', async () => {
    const parser = new MailgunInboundParser({ webhookSigningKey: SIGNING_KEY })
    const input = await buildMailgunRequest(signedFields({ signature: 'short' }))

    await expect(parser.parse(input)).rejects.toBeInstanceOf(AuthError)
  })
})
