import { describe, expect, test } from 'bun:test'
import { PostmarkInboundParser } from '../src/inbound/postmark_parser.ts'
import type { InboundWebhookInput } from '../src/inbound/types.ts'
import { MailInboundError } from '../src/inbound_error.ts'

function webhookInput(payload: unknown): InboundWebhookInput {
  return {
    body: JSON.stringify(payload),
    headers: { 'content-type': 'application/json' },
  }
}

const minimalPayload = {
  From: 'sender@example.com',
  FromName: 'Sender',
  FromFull: { Email: 'sender@example.com', Name: 'Sender' },
  To: 'support@inbox.strav.dev',
  ToFull: [{ Email: 'support@inbox.strav.dev', Name: '', MailboxHash: '' }],
  Subject: 'Help me',
  MessageID: 'postmark-a8c1040e',
  TextBody: 'Hi there',
  Headers: [],
  Attachments: [],
}

describe('PostmarkInboundParser', () => {
  test('parses a minimal payload into canonical shape', async () => {
    const parser = new PostmarkInboundParser()
    const result = await parser.parse(webhookInput(minimalPayload))

    expect(result.from).toEqual({ address: 'sender@example.com', name: 'Sender' })
    expect(result.to).toEqual([{ address: 'support@inbox.strav.dev' }])
    expect(result.cc).toEqual([])
    expect(result.bcc).toEqual([])
    expect(result.subject).toBe('Help me')
    expect(result.text).toBe('Hi there')
    expect(result.html).toBeUndefined()
    expect(result.providerMessageId).toBe('postmark-a8c1040e')
    expect(result.isAutoGenerated).toBe(false)
    expect(result.attachments).toEqual([])
    expect(result.references).toEqual([])
  })

  test('extracts RFC 5322 Message-ID from Headers, not Postmark MessageID field', async () => {
    const parser = new PostmarkInboundParser()
    const result = await parser.parse(
      webhookInput({
        ...minimalPayload,
        MessageID: 'postmark-internal-id',
        Headers: [{ Name: 'Message-ID', Value: '<real-rfc5322-id@example.com>' }],
      }),
    )

    expect(result.messageId).toBe('real-rfc5322-id@example.com')
    expect(result.providerMessageId).toBe('postmark-internal-id')
  })

  test('extracts In-Reply-To and References with angle brackets stripped', async () => {
    const parser = new PostmarkInboundParser()
    const result = await parser.parse(
      webhookInput({
        ...minimalPayload,
        Headers: [
          { Name: 'In-Reply-To', Value: '<parent@example.com>' },
          { Name: 'References', Value: '<root@example.com> <parent@example.com>' },
        ],
      }),
    )

    expect(result.inReplyTo).toBe('parent@example.com')
    expect(result.references).toEqual(['root@example.com', 'parent@example.com'])
  })

  test('header lookup is case-insensitive (Postmark uses mixed case)', async () => {
    const parser = new PostmarkInboundParser()
    const result = await parser.parse(
      webhookInput({
        ...minimalPayload,
        Headers: [
          { Name: 'MESSAGE-ID', Value: '<upper@example.com>' },
          { Name: 'in-reply-to', Value: '<lower@example.com>' },
        ],
      }),
    )

    expect(result.messageId).toBe('upper@example.com')
    expect(result.inReplyTo).toBe('lower@example.com')
  })

  test('detects auto-generated via Auto-Submitted header', async () => {
    const parser = new PostmarkInboundParser()
    const result = await parser.parse(
      webhookInput({
        ...minimalPayload,
        Headers: [{ Name: 'Auto-Submitted', Value: 'auto-replied' }],
      }),
    )

    expect(result.isAutoGenerated).toBe(true)
  })

  test('detects auto-generated via Precedence: bulk', async () => {
    const parser = new PostmarkInboundParser()
    const result = await parser.parse(
      webhookInput({
        ...minimalPayload,
        Headers: [{ Name: 'Precedence', Value: 'bulk' }],
      }),
    )

    expect(result.isAutoGenerated).toBe(true)
  })

  test('does not mark human-submitted as auto (Auto-Submitted: no)', async () => {
    const parser = new PostmarkInboundParser()
    const result = await parser.parse(
      webhookInput({
        ...minimalPayload,
        Headers: [{ Name: 'Auto-Submitted', Value: 'no' }],
      }),
    )

    expect(result.isAutoGenerated).toBe(false)
  })

  test('decodes base64 attachments into Buffer', async () => {
    const parser = new PostmarkInboundParser()
    const original = 'hello world'
    const base64 = Buffer.from(original, 'utf-8').toString('base64')

    const result = await parser.parse(
      webhookInput({
        ...minimalPayload,
        Attachments: [
          {
            Name: 'note.txt',
            ContentType: 'text/plain',
            Content: base64,
            ContentLength: original.length,
            ContentID: null,
          },
        ],
      }),
    )

    expect(result.attachments).toHaveLength(1)
    const [attachment] = result.attachments
    expect(attachment!.filename).toBe('note.txt')
    expect(attachment!.contentType).toBe('text/plain')
    expect(attachment!.content).toBeInstanceOf(Buffer)
    expect(attachment!.content.toString('utf-8')).toBe(original)
    expect(attachment!.size).toBe(original.length)
    expect(attachment!.cid).toBeUndefined()
  })

  test('strips angle brackets from attachment ContentID for inline images', async () => {
    const parser = new PostmarkInboundParser()
    const result = await parser.parse(
      webhookInput({
        ...minimalPayload,
        Attachments: [
          {
            Name: 'logo.png',
            ContentType: 'image/png',
            Content: Buffer.from([0x89, 0x50]).toString('base64'),
            ContentLength: 2,
            ContentID: '<logo-cid@example.com>',
          },
        ],
      }),
    )

    expect(result.attachments[0]!.cid).toBe('logo-cid@example.com')
  })

  test('maps Cc and Bcc recipients', async () => {
    const parser = new PostmarkInboundParser()
    const result = await parser.parse(
      webhookInput({
        ...minimalPayload,
        CcFull: [{ Email: 'cc@example.com', Name: 'Cc Person' }],
        BccFull: [{ Email: 'bcc@example.com', Name: '' }],
      }),
    )

    expect(result.cc).toEqual([{ address: 'cc@example.com', name: 'Cc Person' }])
    expect(result.bcc).toEqual([{ address: 'bcc@example.com' }])
  })

  test('handles Buffer body (not only string)', async () => {
    const parser = new PostmarkInboundParser()
    const buffer = Buffer.from(JSON.stringify(minimalPayload), 'utf-8')
    const result = await parser.parse({ body: buffer, headers: {} })

    expect(result.from.address).toBe('sender@example.com')
  })

  test('throws MailInboundError on invalid JSON', async () => {
    const parser = new PostmarkInboundParser()
    await expect(parser.parse({ body: '{not json', headers: {} })).rejects.toBeInstanceOf(
      MailInboundError,
    )
  })

  test('handles missing Headers and Attachments arrays gracefully', async () => {
    const parser = new PostmarkInboundParser()
    const payload = { ...minimalPayload }
    delete (payload as Partial<typeof minimalPayload>).Headers
    delete (payload as Partial<typeof minimalPayload>).Attachments

    const result = await parser.parse(webhookInput(payload))

    expect(result.headers).toEqual({})
    expect(result.attachments).toEqual([])
    expect(result.messageId).toBeUndefined()
    expect(result.references).toEqual([])
  })

  test('parses Date into Date object when present', async () => {
    const parser = new PostmarkInboundParser()
    const result = await parser.parse(
      webhookInput({ ...minimalPayload, Date: 'Thu, 5 Apr 2018 16:59:01 +0200' }),
    )

    expect(result.date).toBeInstanceOf(Date)
    expect(result.date!.getTime()).toBe(new Date('Thu, 5 Apr 2018 16:59:01 +0200').getTime())
  })
})
